-- !!!! WARNING !!!!
-- This file contains DEVELOPMENT TEST DATA ONLY
-- It will only execute with embedded databases (H2) when spring.sql.init.mode=embedded
-- It will NOT execute with external databases like Oracle
-- DO NOT change spring.sql.init.mode to "always" in production!

INSERT INTO CLIENT (ID, NAME) VALUES ('1', 'Local Development Site');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('1', 'http://localhost');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('1', 'https://localhost');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('1', 'http://localhost:3000');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('1', 'https://localhost:3000');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('1', 'http://localhost:8080');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('1', 'https://localhost:8080');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('1', 'http://localhost:8443');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('1', 'https://localhost:8443');
