INSERT INTO ANALYTICS_EVENT (ID, CLIENT_ID, USER_ID, EVENT, PAGE, EVENT_TIME, IP_ADDRESS, USER_AGENT, BROWSER_LANGUAGE)
VALUES (10000, 'yhr-itm-prod', '04-58-65', 'pageView', '/initial/url', CURRENT_TIMESTAMP, '127.0.0.1', 'Mozilla', 'en-US');
INSERT INTO  ANALYTICS_EVENT_ATTRIBUTE (ANALYTICS_EVENT_ID, ATTRIBUTE_NAME, ATTRIBUTE_VALUE) VALUES (10000, 'appLanguage', 'es');
