INSERT INTO CLIENT (ID, NAME) VALUES ('client1', 'Client 1');
INSERT INTO CLIENT (ID, NAME) VALUES ('client2', 'Client 2');
INSERT INTO CLIENT (ID, NAME) VALUES ('client3', 'Client 3');

INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('client2', 'example2.com');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('client2', 'test2.org');
INSERT INTO AUTHORIZED_CLIENT_ORIGIN (CLIENT_ID, AUTHORIZED_ORIGIN) VALUES ('client3', 'example1.com');
