INSERT INTO SITE (SITE_ID, SITE_NAME) VALUES ('site1', 'Site 1');
INSERT INTO SITE (SITE_ID, SITE_NAME) VALUES ('site2', 'Site 2');
INSERT INTO SITE (SITE_ID, SITE_NAME) VALUES ('site3', 'Site 3');

INSERT INTO SITE_AUTHORIZED_DOMAIN (SITE_ID, DOMAIN) VALUES ('site2', 'example2.com');
INSERT INTO SITE_AUTHORIZED_DOMAIN (SITE_ID, DOMAIN) VALUES ('site2', 'test2.org');
INSERT INTO SITE_AUTHORIZED_DOMAIN (SITE_ID, DOMAIN) VALUES ('site3', 'example1.com');
